name: Bug report
description: File a bug report
labels: [bug, pending triage]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file this bug report.

  - type: textarea
    attributes:
      label: Bug description
      description: A clear and concise description of the bug.
      placeholder: |
        <!--
          What did you do? (Provide reproduction code in next section)

          What did you expect to happen?

          What happened instead?

          Do you have an error stack-trace?
        -->
    validations:
      required: true

  - type: input
    attributes:
      label: Minimal reproduction link
      description: |
        > ⚠️ A minimal reproduction is required to demonstrate the bug, and for us to debug it. If not provided, the issue will be closed.

        Provide a link to a minimal reproduction repository so we can `git clone`, run `npm start`, and reproduce the bug right away.

        Starter template: [fork this template on StackBlitz](https://stackblitz.com/edit/node-guv65j?file=webpack.config.js&view=editor)

        #### Requirements:
        - No more than 10 files
          Delete irrelevant files (e.g. `LICENSE`, `.npmrc`, `.github`). This is the first step of debugging so doing this will save us work.
          👉 **Tip:** The _smaller_ the reproduction, the _faster_ we can debug and resolve your issue

        - Set the `start` script in `package.json` to the command that shows the bug

      placeholder: Minimal reproduction URL
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: |
        Run and paste the output of:
        ```
        npx envinfo --system --npmPackages webpack,esbuild-loader --binaries
        ```
        
        This information is used to for reproduction and debugging.
      placeholder: |
        System:
          OS:
          CPU:
          Shell:
        Binaries:
          Node:
          npm:
        npmPackages:
          webpack:
          esbuild-loader:
      render: shell
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Can you contribute a fix?
      description: We would love it if you can open a pull request to fix this bug!
      options:
        - label: I’m interested in opening a pull request for this issue.

  - type: markdown
    attributes:
      value: |
        Want to escalate this issue and get priority support? Consider becoming a [sponsor](https://github.com/sponsors/privatenumber)! Your sponsorship helps ensure swift bug resolution and ongoing project maintenance. Thank you for your support! 🙏
